### ISSUE TITLE
Looks abandoned

### ISSUE THREAD

**Issue by odahcam** [aleris/zxing-typescript#12]
You can open the repo for mantainers.

**Comment by aleris** [comment]
Sorry, I didn't find time for this, for the moment I do not have time for
it, but I plan to come back to continue. Off course I accept contributions.

I consider the project still in the incipient phase as there are a lot of
bar code types to migrate and each require a sustained effort and
considerable time.

vin., 2 feb. 2018, 13:18 Luiz Machado <notifications@github.com> a scris:

**Comment by odahcam** [comment]
If you want, I can be a caollaborator/mantainer and push directly to a `develop` branch here instead of mantaining my own branch.

**Comment by noru** [comment]
also got some cross-browser issues, anyway I can help with this?

**Comment by aleris** [comment]
@odahcam Sure let's give it a go. 
Please see in Projects for the plan I had in mind. I already started working on pdf417 so you might want to skip that. Please also see [typescriptport.md](https://github.com/aleris/zxing-typescript/blob/master/typescriptport.md) for the rules I used, if you feel like changing something please let me know. Because of intensive use of bit manipulation some are tricky to port, the file above contain some info. Please let me know if I can help with something going forward. The main work to go forward is to implement new code bars as listed in the project plan. Off course, we can consult If you feel like changing something. 

@noru  I think the best would be to make a PR?

**Comment by odahcam** [comment]
All right @aleris , what I've done until now:
 -  Code refactoring (nothing too complex), to improve maintainbility following @codacy and @codeclimate reports (which are made using linters as TSLint).
 - Renamed some tests.
 - Rewrited some test's methods, to make them faster. The cause was that Travis-CI could not build the project due to tests timeout, now Travis-CI builds pass ~65% of the time, before was ~0%.
 - Created new publish, which includes *typings*, so people can use this with TypeScript properly, for example I'm using with Angular 5 in an enterprise project.

That's what I can remember, when I make any update I'll documentate exactly what it is.

Thanks.

**Comment by aleris** [comment]
@odahcam Sound good. 

Please keep in mind that any deviation from original zxing java code base would make future updates difficult, so any change like test renaming should be done only if necessary (eg, test renamed). 

The test problems sound strange, I didn't have any problem like that, it worked for me 100% of a time (except proper fails off course). Did you change something in the workflow, added something to the build process, etc? If yes, you may want to reconsider it.

**Comment by odahcam** [comment]
Well, in that case I think I should make a compare to this master branch to see exactly what was changed. But in short I can say that I didn't changed anything too much, I'm a little newbie at TypeScript, so I tryied not to do complex things.

For now I can say that I've made changes to build so the package could fit TypeScript and NPM deployment recomendations and rules.

**Comment by aleris** [comment]
The best approach would be to make small incremental changes and push to
main in steps if everything looks good.

În sâm., 3 feb. 2018 la 19:09, Luiz Machado <notifications@github.com> a
scris:

**Comment by odahcam** [comment]
My main problem is that I need some changes ASAP, so I will keep improving my fork, then I will start to bring things by small merges to here again.

Also, I have my tests performance issue, that I'd like to discuss: https://github.com/odahcam/zxing-ts/issues/5
