### ISSUE TITLE
Only works with example Image

### ISSUE THREAD

**Issue by IshaqBhojaniGenetech** [aleris/zxing-typescript#3]
Hi there, 
I finally successfully installed with angular 4 and typescript. but its only decode the QR code you have provided in example. 

Its not working with any other QR code. 

I have tried following images.

1.
![download](https://user-images.githubusercontent.com/31653151/31939428-ca29e4a2-b8d3-11e7-8c26-1425c9f50c76.png)
2.
![code128](https://user-images.githubusercontent.com/31653151/31939431-cd4c96de-b8d3-11e7-8f22-9b246b4fedfe.png)
3.
![22810301_813199782175429_385919422_o](https://user-images.githubusercontent.com/31653151/31939446-dc8bd29a-b8d3-11e7-8ed9-50c22288f39f.jpg)
4.
![dd](https://user-images.githubusercontent.com/31653151/31939453-e10ac768-b8d3-11e7-8818-b292aaab6997.png)

It only works with.
![qrcode-image](https://user-images.githubusercontent.com/31653151/31939483-fb985be0-b8d3-11e7-8d6a-7c90f3f2d64a.png)

Here is my code.

```
onImageSelect(e) {
    const codeReader = new BrowserQRCodeReader();
    const myReader = new FileReader();

    myReader.onload = (event) => {
      codeReader.decodeFromImage(undefined, event.target['result'])
        .then((result) => {
          console.log(result['text']);
        }).catch((err) => {
        console.log(err);
      });
    };

    myReader.readAsDataURL(e.target.files[0]);
  }
```
Here is the error log
`Exception {type: "NotFoundException", message: undefined}`

is there anything wrong I am doing?

**Comment by aleris** [comment]
Hi,

It is a problem with the library itself not with your code for 1 and 4. Strange is that according with a test case I quickly build for case 1 it passes on nodejs side, however it does not work from browser and case 4 does not work at all even if it seems like a pretty simple and standard one. I will have to investigate it further.
 
2 and 3 are not QR codes, are UPC. These are not implemented yet, are included [in roadmap](https://github.com/aleris/zxing-typescript#status-and-roadmap) in "oned" submodule but will take some time to get there.

**Comment by IshaqBhojaniGenetech** [comment]
OK great, Any idea how much time it will take to fix this issue?

**Comment by aleris** [comment]
I do not currently have a focus on this project and will probably advance very slowly. 
The problem for this one was very simple, but hard to spot, because it manifested for some type of images only, here is the fix:
https://github.com/aleris/zxing-typescript/commit/6c8e45939a5b23199652ad39dc77cd205cc19c06#diff-80c1be98d55c33dbadd1cc608aa591b6L27
