### ISSUE TITLE
Exact DeviceID not working

### ISSUE THREAD

**Issue by werthdavid** [aleris/zxing-typescript#4]
The method BrowserCodeReader.decodeFromInputVideoDevice() accepts a device-id as input-parameter. Unfortunately this seems to be ignored (for some Browsers only? Safari iOS 11 is the only device I have for testing that has multiple cameras).

**Comment by werthdavid** [comment]
I created a PR

**Comment by aleris** [comment]
Doesn't seem to brake anything in chrome so I merged this as is.
