### ISSUE TITLE
Does it support 1D barcodes(UPC, EAN)?

### ISSUE THREAD

**Issue by prajjwold** [aleris/zxing-typescript#6]

**Comment by aleris** [comment]
No, it is on the [roadmap](https://github.com/aleris/zxing-typescript#status-and-roadmap) but will take some time to get there.

**Comment by nmelhado** [comment]
Has this been added yet?

**Comment by odahcam** [comment]
Yes, here: https://github.com/zxing-js/library

**Comment by nmelhado** [comment]
Great, thank you!
